import os
import openai
import json

class OpenAIClient:
    def __init__(self):
        self.client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    
    def generate_playlist(self, prompt, song_count):
        response = self.client.chat.completions.create(
            model="gpt-4-turbo",
            messages=[
                {
                    "role": "system",
                    "content": "You are MusicGPT, the world's best music playlist generator AI. Your task is to ALWAYS create complete music playlists based on a user's description of a mood, vibe, activity, or feeling. You must: - ONLY suggest real, existing songs and real artists. - Prioritize popular and recognizable songs (globally or culturally).- If the user's description is vague or unclear, you MUST still create a playlist by intelligently guessing their intended mood. - Make sure all songs fit well together stylistically and emotionally. - If the user's input is vague, intelligently guess their intended music style. - NEVER leave the playlist empty. - DO NOT invent fake songs or unknown artists. Respond ONLY by filling the provided JSON format exactly."
                },
                {
                    "role": "user",
                    "content": f"Create a playlist that contains exactly {song_count} songs. No more, no less that fits the following description '''{prompt}'''. The playlist should include real, popular songs that match the mood or activity well. Ensure musical consistency across the playlist. Do NOT invent songs or artists. If the description is unclear, guess intelligently. Always create a full playlist of real, popular songs."
                },
            ],
            functions=[
                {
                    "name": "create_playlist",
                    "description": "Creates a spotify playlist based on a list of songs that should be added to the list.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "playlist_name": {
                                "type": "string",
                                "description": "Name of playlist",
                            },
                            "playlist_description": {
                                "type": "string",
                                "description": "Description for the playlist. Please add that this playlist was generated by an AI.",
                            },
                            "songs": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "songname": {
                                            "type": "string",
                                            "description": "Name of the song that should be added to the playlist",
                                        },
                                        "artists": {
                                            "type": "array",
                                            "description": "List of all artists",
                                            "items": {
                                                "type": "string",
                                                "description": "Name of artist of the song",
                                            },
                                        },
                                    },
                                    "required": ["songname", "artists"],
                                },
                            },
                        },
                        "required": ["songs", "playlist_name", "playlist_description"],
                    },
                }
            ],
        )
        return json.loads(response.choices[0].message.function_call.arguments)
