import os
import openai
import json

class OpenAIClient:
    def __init__(self):
        self.client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    
    def generate_playlist(self, prompt, song_count):
        response = self.client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {
                    "role": "system",
                    "content": "You are MusicGPT, world's best music recommendation AI. Given a description of a users music preferences, you will recommend songs tailored to the user's preferences."
                },
                {
                    "role": "user",
                    "content": f"Create a playlist with {song_count} songs that fits the following description '''{prompt}'''. Come up with a creative and unique name for the playlist."
                },
            ],
            functions=[
                {
                    "name": "create_playlist",
                    "description": "Creates a spotify playlist based on a list of songs that should be added to the list.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "playlist_name": {
                                "type": "string",
                                "description": "Name of playlist",
                            },
                            "playlist_description": {
                                "type": "string",
                                "description": "Description for the playlist. Please add that this playlist was generated by an AI.",
                            },
                            "songs": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "songname": {
                                            "type": "string",
                                            "description": "Name of the song that should be added to the playlist",
                                        },
                                        "artists": {
                                            "type": "array",
                                            "description": "List of all artists",
                                            "items": {
                                                "type": "string",
                                                "description": "Name of artist of the song",
                                            },
                                        },
                                    },
                                    "required": ["songname", "artists"],
                                },
                            },
                        },
                        "required": ["songs", "playlist_name", "playlist_description"],
                    },
                }
            ],
        )
        return json.loads(response.choices[0].message.function_call.arguments)
